### ISSUE TITLE
esp32 dev board issue

### ISSUE THREAD

**Issue by pan-sattan** [zs6buj/FrSky-Passthru-To-WiFi-and-or-Bluetooth#1]
Hi, its me... again :D
I finally had some time and hardware comes... but I am not able to run it on my board...

![2021-07-27 08_41_06-FrSkyToWiFi - config h _ Arduino 1 8 15_2](https://user-images.githubusercontent.com/59567959/127107847-227d7c39-f000-4ff0-93cb-b88fbd3bc146.png)
![2021-07-27 08_40_40-FrSkyToWiFi - config h _ Arduino 1 8 15](https://user-images.githubusercontent.com/59567959/127107917-b954e8cf-1a36-4bb8-be6b-2bf39e489bd6.png)

**Comment by zs6buj** [comment]
Hi pan-sattan

Good you received your new board.

Are you sure your board has 16MB of flash, as you have selected. Maybe show me a link.

Try this:
Under Flash Size, select 4MB
Under Partition Scheme, select "Minimal spiffs(1.9MB .........

![image](https://user-images.githubusercontent.com/12892533/127142329-52e3de5d-8d9a-4786-b173-5661c4a55ce1.png)

**Comment by pan-sattan** [comment]
I tried with different Partition Scheme and now seems its working... I have to test it more briefly at home later

**Comment by pan-sattan** [comment]
looks like its working... I have to test it on the field...

![image](https://user-images.githubusercontent.com/59567959/127459457-e4cb2e30-21f1-4bca-b460-b45b4c7df222.png)

**Comment by pan-sattan** [comment]
Now it looks like this... but I get GPS only from my flat

[tracker.txt](https://github.com/zs6buj/FrSky-Passthru-To-WiFi-and-or-Bluetooth/files/6900325/tracker.txt)

**Comment by zs6buj** [comment]
pan-sattan, could you please test using the latest version, and uncomment this debug option

#define Debug_FrSky_Messages

**Comment by pan-sattan** [comment]
looks like there is something wrong:

![image](https://user-images.githubusercontent.com/59567959/127865590-948c439f-e1a5-4e85-aa4a-12cea4fe127b.png)

![image](https://user-images.githubusercontent.com/59567959/127865637-bbb0fc4d-9f39-4bd1-8075-415bbff74cc9.png)

**Comment by pan-sattan** [comment]
with Frsky UDP I have this LOG:

Starting AntTrack version:2.18.03
Display support activated: Landscape 
64x128  text_size=1  char_w_px=6  char_h_px=8  scr_h_ch=8  scr_w_ch=21
Target Board is ESP32 / Variant is Dev Module
FrSky UDP In
Selected protocol is F.Port 1
headingSource = Tracker Box Compass
Compass type HMC5883L expected
Trying to connect to FrSkyToWiFi......
WiFi connected!
Local IP address: 192.168.4.2
WiFi RSSI:-49 dBm
Frs UDP instance started, listening on IP 192.168.4.2, UDP port 14551
FrSky read good!

pt_gp_fix=0 pt_gps_homefix =0 pt_gp_homereset=0 pt_gps_accuracy =2 pt_gps_numsats=38
 FrSky 0x840 heading=279.0
 FrSky 0x800 longitude=XX.2442150
 FrSky 0x800 latitude=YY.58YY915
 FrSky 0x820 altitude=277.0
pt_gp_fix=0 pt_gps_homefix =0 pt_gp_homereset=0 pt_gps_accuracy =2 pt_gps_numsats=38
 FrSky 0x840 heading=279.0
 FrSky 0x800 longitude=XX.2442131
 FrSky 0x800 latitude=YY.58YY838
 FrSky 0x820 altitude=278.0
pt_gp_fix=0 pt_gps_homefix =0 pt_gp_homereset=0 pt_gps_accuracy =2 pt_gps_numsats=38
 FrSky 0x840 heading=279.0
 FrSky 0x800 longitude=XX.2442112
 FrSky 0x800 latitude=YY.58YY800
 FrSky 0x820 altitude=278.0
pt_gp_fix=0 pt_gps_homefix =0 pt_gp_homereset=0 pt_gps_accuracy =2 pt_gps_numsats=38
 FrSky 0x840 heading=279.0
 FrSky 0x800 longitude=XX.2442093
 FrSky 0x800 latitude=YY.58YY762
 FrSky 0x820 altitude=278.0
pt_gp_fix=0 pt_gps_homefix =0 pt_gp_homereset=0 pt_gps_accuracy =2 pt_gps_numsats=38
 FrSky 0x840 heading=279.0
 FrSky 0x800 longitude=XX.2442074
 FrSky 0x800 latitude=YY.58YY686
 FrSky 0x820 altitude=278.0
pt_gp_fix=0 pt_gps_homefix =0 pt_gp_homereset=0 pt_gps_accuracy =2 pt_gps_numsats=38
 FrSky 0x840 heading=279.0
 FrSky 0x800 longitude=XX.2442074
 FrSky 0x800 latitude=YY.58YY648
 FrSky 0x820 altitude=279.0
pt_gp_fix=0 pt_gps_homefix =0 pt_gp_homereset=0 pt_gps_accuracy =2 pt_gps_numsats=38
 FrSky 0x840 heading=279.0
 FrSky 0x800 longitude=XX.2442055
 FrSky 0x800 latitude=YY.58YY609
 FrSky 0x820 altitude=279.0
pt_gp_fix=0 pt_gps_homefix =0 pt_gp_homereset=0 pt_gps_accuracy =2 pt_gps_numsats=38
 FrSky 0x840 heading=279.0
 FrSky 0x800 longitude=XX.2442036
 FrSky 0x800 latitude=YY.58YY533
 FrSky 0x820 altitude=279.0
pt_gp_fix=0 pt_gps_homefix =0 pt_gp_homereset=0 pt_gps_accuracy =0 pt_gps_numsats=83
 FrSky 0x840 heading=258.0
 FrSky 0x800 longitude=XX.2439671
 FrSky 0x800 latitude=YY.5852852
 FrSky 0x820 altitude=267.0
pt_gp_fix=0 pt_gps_homefix =0 pt_gp_homereset=0 pt_gps_accuracy =0 pt_gps_numsats=83
 FrSky 0x840 heading=258.0
 FrSky 0x800 longitude=XX.2439709
 FrSky 0x800 latitude=YY.5852966
 FrSky 0x820 altitude=267.0
pt_gp_fix=0 pt_gps_homefix =0 pt_gp_homereset=0 pt_gps_accuracy =0 pt_gps_numsats=83
 FrSky 0x840 heading=258.0
 FrSky 0x800 longitude=XX.2439747
 FrSky 0x800 latitude=YY.5853081
 FrSky 0x820 altitude=268.0

**Comment by pan-sattan** [comment]
![20210802_153034](https://user-images.githubusercontent.com/59567959/127870059-b6173bf4-4381-4f4e-b864-af74ad028088.jpg)
![20210802_153025](https://user-images.githubusercontent.com/59567959/127870062-562e40e4-fd8e-4d1a-8861-d80447eadc51.jpg)

**Comment by zs6buj** [comment]
Could you remind me how you are getting the FrSky UDP. Is it from the r9m, then into ?

**Comment by pan-sattan** [comment]
frsky r9 with fport fw - module s.port output to esp32 dev board and then ap wifi udp to another esp32 dev board

**Comment by zs6buj** [comment]
Ok, I'll get back to you.

**Comment by zs6buj** [comment]
The fact that the sensor information displayed on the Taranis is bad suggests that the problem could already be present on the flight controller side.

**Comment by pan-sattan** [comment]
no, its correct... I am using inav lua script and all Telemetry informations are the same like it should be e.g. when I connect it to betaflight configurator, I can see number of satelites and gps, etc.

**Comment by pan-sattan** [comment]
when I was decoded by myself... this was my translate...

...code is not complete

//*#*#*#*#*#*#*#*# GPS_Stats #*#*#*#*#*#*#*#*#*

#define INAV_GPS_STATE_DATA_ID              0x0410 // Tmp2 0410 GPS-status!

      case INAV_GPS_STATE_DATA_ID:
        gpsState = (int32_t)data;
        return appId;
/*   
    Taranis values
   Tmp1(@C)  Tmp2(@C)
    30001     1708
    10005     3709
    20015     3924
*/

#if defined  FAKE_numbers 
int GpsState = 3707;
#else 
int GpsState = inav.getGpsState();
#endif

/*  https://docs.px4.io/master/en/peripherals/frsky_telemetry.html  */
  String gps_status;
  int32_t fr_gps_status_inav = GpsState;
  String fr_gps_status_strg = (String) fr_gps_status_inav;
  String fr_gps_status_sub = fr_gps_status_strg.substring(0,1);
  int gps_status_int = fr_gps_status_sub.toInt();
    
  if      (gps_status_int == 0)  gps_status = ("GPS no Fix"); 
  else if (gps_status_int == 1)  gps_status = ("GPS Fix"); 
  else if (gps_status_int == 2)  gps_status = ("GPS 2D Fix"); 
  else if (gps_status_int == 3)  gps_status = ("GPS 3D Fix"); 
  
  String gps_HDOP_sub = fr_gps_status_strg.substring(1,2);
  int gps_HDOP_int = gps_HDOP_sub.toInt();
  int gps_HDOP = gps_HDOP_int;

  String gps_sats_sub = fr_gps_status_strg.substring(2,4);
  int gps_sats_int = gps_sats_sub.toInt();
  int gps_sats = gps_sats_int;

#if defined  GPS_status_info || defined  Debug_All
  Serial.println("GPS_status_info"); 
  Serial.print("GPS_value: "); Serial.println(GpsState); 
  Serial.print("GPS_status: "); Serial.println(gps_status);                           
  Serial.print("GPS_HDOP (0 - 9): "); Serial.println(gps_HDOP);
  Serial.print("GPS_sats: "); Serial.println(gps_sats); 
  Serial.println(); 
#endif

**Comment by zs6buj** [comment]
So you are saying this data is correct?

![image](https://user-images.githubusercontent.com/12892533/127967855-3fe14626-9087-4aa5-8fb7-eb93d3d88880.png)

**Comment by pan-sattan** [comment]
yes, I had 7 satelites catched... was confirmed via betaflight configurator menu there

**Comment by zs6buj** [comment]
Ah, so you are using PX4 firmware on your flight controller, and px4 now supports FrSky S.Port telemetry. This is news to me, but very welcome.

**Comment by pan-sattan** [comment]
no, I am using betaflight... I just used informations from this page for Tmp2 decoding in past

**Comment by zs6buj** [comment]
Ok, but if you are using OpenTX on Taranis, you should be able to display sensor data, like GPS, voltages, alt etc after scanning for sensors?

If I remember correctly, when you connect by serial from rm9 to Taranis it all works?

**Comment by zs6buj** [comment]
Are you using my FrSky to UDP/BT https://github.com/zs6buj/FrSky-Passthru-To-WiFi-and-or-Bluetooth. Then I can debug in there..

**Comment by pan-sattan** [comment]
yes this one... and I tried different port types... still the same result. 
it showing to me good gps coords. but wrong satelites number 
![16279791943595156431880192595129](https://user-images.githubusercontent.com/59567959/127983566-3bff113f-7e32-4933-bcce-ed54eff409c0.jpg)

**Comment by zs6buj** [comment]
ok, I'll check it

**Comment by pan-sattan** [comment]
maybe my settings are wrong... duno
I have to try all variants

**Comment by pan-sattan** [comment]
now I tried to connect RX directly to esp32 - serial port connection and auto protocol select S.Port with the same message like abowe. Then I changed protocol to F.Port1 and there was no message

![image](https://user-images.githubusercontent.com/59567959/128004129-dbe1408f-f121-4c22-a4c2-85db3bd53f60.png)

**Comment by zs6buj** [comment]
Pan, I have not forgotten about you. 

I've setup a matched pair of apps for you:

- FrSkyToWiFiBT v0.0.4 already setup for FrSky S.Port serial in (from back of R9M) and BT out
- AntTrack v2.18.04 already set up for FrSky BT in, with matching BT slave name from above

Just make sure you select your ESP32 Dev Kit boards, and recompile. I tested the two together and they work here.


You will find them on my github/zs6buj

**Comment by pan-sattan** [comment]
good to hear... I will check it soon

**Comment by pan-sattan** [comment]
hi, it showing to me good amount of sats until its fixed, then i see in radio 5sats and in console 37 
![20210807_095122](https://user-images.githubusercontent.com/59567959/128593150-f796ce04-d152-49bf-adea-c56b58673bb3.jpg)
![20210807_095118](https://user-images.githubusercontent.com/59567959/128593156-ddc80ace-c002-473c-89c0-b19d2a22a6c6.jpg)

**Comment by zs6buj** [comment]
Hi pan-sattan,

ok, I think I see what is happening. I have not paid much attention to FkSky D mode telemetry, and it is clear that an X frame is coming thru with ID 0x410 - tmp2 gps status, and something is going wrong with my decode.

I found this in the iNav documentation:

* **Tmp2** : GPS lock status, accuracy, home reset trigger, and number of satellites. Number is sent as **ABCD** detailed below. Typical minimum GPS 3D lock value is 3906 (GPS locked and home fixed, HDOP highest accuracy, 6 satellites).
  * **A** : 1 = GPS fix, 2 = GPS home fix, 4 = home reset (numbers are additive)
  * **B** : GPS accuracy based on HDOP (0 = lowest to 9 = highest accuracy)
  * **C** : number of satellites locked (digit C & D are the number of locked satellites)
  * **D** : number of satellites locked (if 14 satellites are locked, C = 1 & D = 4)

**Comment by zs6buj** [comment]
Ok, I rewrote the code to unpack tmp2 id = 0x410, and included some more debugging for it.

Please could you try v2.18.5 again and post the monitor log.

**Comment by pan-sattan** [comment]
![20210809_130030](https://user-images.githubusercontent.com/59567959/128696776-7e4c340a-792a-48c7-a140-09f2c55e62e8.jpg)
![20210809_130021](https://user-images.githubusercontent.com/59567959/128696782-047ba08f-8228-40e8-a378-d31a4c2c4d2b.jpg)

**Comment by pan-sattan** [comment]
@zs6buj is that good? tomorrow I will test it on filed

**Comment by zs6buj** [comment]
Sorry, I missed a line. Please download and try again.

**Comment by pan-sattan** [comment]
I had edited the debug options and put there RSSI...

pt_gp_fix=0 pt_gps_homefix =0 pt_gp_homereset=4 pt_gps_accuracy =3 pt_gps_numsats=0
 FrSky 0x840 heading=69.0
 FrSky F101: RSSI=66
 FrSky 0x800 longitude=17.2441483
 FrSky 0x800 latitude=49.5857658
 FrSky 0x820 altitude=223.0
 FrSky F101: RSSI=60
 FrSky 0x840 heading=91.0
 FrSky F101: RSSI=70
 FrSky 0x800 longitude=17.2441387
 FrSky 0x800 latitude=49.5857620
 FrSky 0x820 altitude=223.0
 FrSky 0x840 heading=78.0
 FrSky F101: RSSI=70
 FrSky 0x800 longitude=17.2441235
 FrSky 0x800 latitude=49.5857849
 FrSky 0x820 altitude=221.0
0x410 payload  b0:227  b1:5 B2:0  b3:0
pt_gp_fix=1 pt_gps_homefix =2 pt_gp_homereset=0 pt_gps_accuracy =5 pt_gps_numsats=0
 FrSky F101: RSSI=66
 FrSky 0x840 heading=92.0
 FrSky F101: RSSI=60
 FrSky 0x800 longitude=17.2440968
 FrSky 0x800 latitude=49.5857620
 FrSky 0x820 altitude=221.0
0x410 payload  b0:225  b1:5 B2:0  b3:0
pt_gp_fix=1 pt_gps_homefix =0 pt_gp_homereset=0 pt_gps_accuracy =5 pt_gps_numsats=0
 FrSky F101: RSSI=60
 FrSky 0x840 heading=77.0
 FrSky F101: RSSI=70

**Comment by zs6buj** [comment]
Thanks. We are getting there. Please could you do the same, but activate

#define Debug_FrPort_Stream

**Comment by pan-sattan** [comment]
then I can see something like this:
I am waiting for GPS fix and lot/lan values now... hard to reach here :D

7E<98<10<01<F1<64<00<00<00<98<
7E<00<10<40<52<ED<FF<FF<FF<6F<
7E<00<10<00<07<00<00<00<00<E8<
7E<00<10<10<07<FD<FF<FF<FF<DA<
7E<00<10<20<07<65<00<00<00<63<
7E<00<10<00<01<0B<00<00<00<E3<
7E<00<10<10<01<00<00<00<00<DE<
7E<00<10<00<04<32<75<00<00<44<
7E<00<10<10<04<00<00<00<00<DB<
7E<00<10<01<04<24<00<00<00<C6<
7E<98<10<04<F1<58<00<00<00<A1<
7E<98<10<01<F1<64<00<00<00<98<

**Comment by zs6buj** [comment]
Yes, please can you continue printing and wait for gps fix. You can put the monitor log into a .txt file.

**Comment by pan-sattan** [comment]
its somwehere there ;) around 14:23:00 should be fully fixed
[LOG.txt](https://github.com/zs6buj/FrSky-Passthru-To-WiFi-and-or-Bluetooth/files/6961656/LOG.txt)

**Comment by zs6buj** [comment]
Pan, I need this one ALSO to remain as before:

#define Debug_FrSky_Messages

**Comment by zs6buj** [comment]
Actually, I have enough information for now. No need to do the above.

**Comment by pan-sattan** [comment]
here is it all together... sorry @zs6buj 
[LOG2.txt](https://github.com/zs6buj/FrSky-Passthru-To-WiFi-and-or-Bluetooth/files/6963210/LOG2.txt)

**Comment by zs6buj** [comment]
Please try v2.18.06. The way the 0x410 frame is composed is bizarre, but I think I got it. It's been tricky without test telemetry, so thanks for the help.

Please activate #define Debug_FrPort_Stream

**Comment by pan-sattan** [comment]
thank you too... I put there both debug options like before.... 

[LOG.txt](https://github.com/zs6buj/FrSky-Passthru-To-WiFi-and-or-Bluetooth/files/6970770/LOG.txt)

**Comment by pan-sattan** [comment]
is there something what I can do on my side? what to aim for?
as I wrote here https://github.com/zs6buj/FrSky-Passthru-To-WiFi-and-or-Bluetooth/issues/1#issuecomment-891540553
Tmp2 value is divided to segments

**Comment by pan-sattan** [comment]
and I used this:
https://github.com/variostudio/FrSkySportTelemetry

**Comment by zs6buj** [comment]
Good morning @pan-sattan 

It looks like numsats is now correct, so you can try it without the debugging macros.

My apologies for not realising the significance of iNav and D mode in your early posts, and thank you for your code suggestions. They look on the right track to me. Of course, I want to ensure that the AntTrack firmware is correct first.

**Comment by pan-sattan** [comment]
morning... so now if I disable debug options, it should work properly with latest version of tracker?

**Comment by zs6buj** [comment]
yes

**Comment by pan-sattan** [comment]
I dont have good news... 
went out and tracker doesnt move... I catched about 12 sats, fully fixed in OSD, all debug options disabled (kept only #define Debug_Minimum and #define Debug_Status)

https://youtu.be/5IXdlJM9tNo

![vlcsnap-2021-08-16-14h18m52s626](https://user-images.githubusercontent.com/59567959/129562747-ef2262b8-eb41-4db8-8e45-5163e3e33b06.png)

**Comment by zs6buj** [comment]
Ok, so now I believe we are getting good data in. We are making progress.  Let's check the next steps.

If you have satellite lock, and you have headingSource = Tracker Box Compass, and AntTrack has received and remembered home location, and if you have moved more than minDist (4metres) from home, the servos should move. Now let's debug azimuth and elevation calculations , and then servo movement.

Please run with these debug macros and copy the monitor log into a .txt file and publish here.

#define Debug_FrSky_Messages
#define Debug_AzEl
#define Debug_Servos

**Comment by pan-sattan** [comment]
servos are working...
but in your code is commented TestServos(); 

>AntTrack.ino row #576

  #if defined Debug_Servos  
    Log.println("Testing Servos");
    TestServos();    // Fine tune MaxPWM and MinPWM in Config tab
  #endif  

and for debug of compass there are missing some things I thing... row #1140

void DisplayHeadingSource() {
#if defined Debug_Minimum || defined Debug_All || defined Debug_boxCompass  
  if (headingSource == 1)  {
      Log.println("headingSource = FC GPS"); 
      LogScreenPrintln("HdgSrce=FC GPS");
  }
  else if  (headingSource == 2) { 
      Log.println("Heading source = FC Compass");
      LogScreenPrintln("Headg srce=FC Mag");
  }
  else if (headingSource == 3)   {
      Log.println("headingSource = Tracker Box Compass"); 
      LogScreenPrintln("HdgSrce=Trackr Cmpss");
  }
  else if (headingSource == 4)  {
      Log.println("Dynamic heading source = Tracker Box Compass"); 
      LogScreenPrintln("Dynamic HeadingSrce");
  }  

#endif  
}

I can see only this info:

Starting AntTrack version:2.18.06
Display support activated: Landscape 
64x128  text_size=1  char_w_px=6  char_h_px=8  scr_h_ch=8  scr_w_ch=21
Target Board is ESP32 / Variant is Dev Module
FrSky Bluetooth In
Selected protocol is S.Port
headingSource = Tracker Box Compass
Compass type HMC5883L expected
----- Compass Found -----
Sensor:       HMC5883
Driver Ver:   1
Unique ID:    12345
Max Value:    800.00 uT
Min Value:    -800.00 uT
Resolution:   0.20 uT
--------------------------

Frs bluetooth master mode looking for slave name Frs2BT

**Comment by zs6buj** [comment]
So it looks like its waiting for the BT connection:

You say you got this:

"Frs bluetooth master mode looking for slave name Frs2BT"

then nothing else.

This code simply moves the servos to their limits as a test. You can comment the code out if you don't want it

//#if defined Debug_Servos
//Log.println("Testing Servos");
//TestServos(); // Fine tune MaxPWM and MinPWM in Config tab
//#endif

**Comment by pan-sattan** [comment]
yes, because I want to double check if all components are working as expected... we have rainy today... I cant fly and test it

**Comment by pan-sattan** [comment]
Hi, finally I was on field ant this is the LOG... I used this debug options... but cannot see AzEl and other values..!

#define Debug_Minimum    //  Leave this as is unless you need the serial port for something else
#define Debug_Status
#define Debug_AzEl
#define Debug_boxCompass  
#define Debug_FrSky_Messages

[tracker_logs.txt](https://github.com/zs6buj/FrSky-Passthru-To-WiFi-and-or-Bluetooth/files/7014257/tracker_logs.txt)

**Comment by zs6buj** [comment]
Hi, thank you for your tracker_logs.txt.

I have added and extra debug for FrSky. Please could you compile and flash v2.18.07 and rerun as before, but with these debugs activated

#define Debug_FrSky_Messages
#define Debug_Frsky_GPSHdg_Status

**Comment by pan-sattan** [comment]
OK, looks like all is good...
but homefix is NOK

pt_gp_fix=1 pt_gps_homefix =0 pt_gp_homereset=0 pt_gps_accuracy =8 pt_gps_numsats=12
gpsGood:1  hdopGood:1  lonGood:1  latGood:1  altGood:1  hdgGood:1  boxhdgGood:1 

[LOG.txt](https://github.com/zs6buj/FrSky-Passthru-To-WiFi-and-or-Bluetooth/files/7022422/LOG.txt)

**Comment by zs6buj** [comment]
Thanks for the feedback. I I do not have a test setup available right now.

I've added a bit more debugging code to v2.18.07. Could you run it again please.

#define Debug_FrSky_Messages
#define Debug_Frsky_GPSHdg_Status

**Comment by pan-sattan** [comment]
here new LOG

[LOG.txt](https://github.com/zs6buj/FrSky-Passthru-To-WiFi-and-or-Bluetooth/files/7025670/LOG.txt)

**Comment by zs6buj** [comment]
Thanks for the feedback. 

I've added even more debugging code to v2.18.07. Could you download, flash and run it again please.

#define Debug_FrSky_Messages
#define Debug_Frsky_GPSHdg_Status

But, please post .txt from the beginning. Thanks pan-sattan

**Comment by pan-sattan** [comment]
thank you too for your effort

I found there this message:

pt_gp_fix=1 pt_gps_homefix=0 pt_gp_homereset=0 pt_gps_accuracy=8 pt_gps_numsats=11
gpsGood:1  hdopGood:1  lonGood:1  latGood:1  altGood:1  hdgGood:1  boxhdgGood:1 
Good flight computer GPS lock
gpsGood:1  hdopGood:1  lonGood:1  latGood:1  altGood:1  hdgGood:1  boxhdgGood:1 

[LOG.txt](https://github.com/zs6buj/FrSky-Passthru-To-WiFi-and-or-Bluetooth/files/7027186/LOG.txt)

**Comment by zs6buj** [comment]
Now we have this:

"Good flight computer GPS lock
GPS lock good! Push set-home button (pin:18) anytime to start tracking"

This is what I was looking for. So now try with only these

#define Debug_FrSky_Messages
#define Debug_AzEl
#define Debug_Servos


Push the button to rememberhome, and then move more than 4m from home.

**Comment by pan-sattan** [comment]
ok, but I thought... if is it locked, it will start tracking automatically

**Comment by zs6buj** [comment]
We could set it up that it saves home coordinates when it gets GPS lock, but many people prefer to push the button when they are ready. There is also a LED, which flashes slow when telemetry connects, faster when GPS lock achieved and solid when button pressed and home set.

**Comment by pan-sattan** [comment]
sorry, I was busy last days... tomorrow I will test it, but for drones maybe will be better to activate tracking after arm switch on position?

**Comment by zs6buj** [comment]
Since you are using Betaflight and D-style telemetry, I am not aware of a sensor type / message type that will tell me arming status.

In X-style telemetry I can use message type 0x5001, but your telemetry looks like D-style

**Comment by pan-sattan** [comment]
It uses this data:

#define INAV_FLIGHT_MODE_DATA_ID            0x0400 // Tmp1 sensor

//*#*#*#*#*#*#*#*# Flight_Flag #*#*#*#*#*#*#*#*#*
String MODE_flag = MODE_strg.substring(4);
int fMODE_int = MODE_flag.toInt();
String fMODE;

if      (fMODE_int == 1)  fMODE = ("OK_to_ARM"); 
else if (fMODE_int == 2)  fMODE = ("PREVENT_Arming"); 
else if (fMODE_int == 4)  fMODE = ("ARMED");

**Comment by zs6buj** [comment]
I just pushed v2.18.08  Add debug for FrSky D-Style Flight Mode 0x400

With this I can find the 0x400 message if it comes through, and see what changes in the payload when you arm the drone.

It's in the Debug folder. Could you please compile, flash and run, and post log. Include switch to "ARM" mode during debug run.

**Comment by pan-sattan** [comment]
Thank you...
I went out and tested tracker... I had 15 satelites, locked GPS, and after pushing button on tracker nothing happened (PIN_18 + GND)
Now I am gona to upload your new code

**Comment by pan-sattan** [comment]
In file included from C:\Temp\arduino_modified_sketch_77139\AntTrack.ino:126:0:
config.h:864:2: error: invalid preprocessing directive #defined
 #defined Debug_FrSkyD_Flight_Mode
  ^
exit status 1
invalid preprocessing directive #defined

so I repaired that one... but 

In file included from C:\Temp\arduino_modified_sketch_995622\AntTrack.ino:126:0:
config.h:8:28: error: invalid digit "8" in octal constant
 #define PATCH_LEVEL        08
                            ^
C:\Temp\arduino_modified_sketch_995622\AntTrack.ino:339:93: note: in expansion of macro 'PATCH_LEVEL'
   snprintf(snprintf_buf, snp_max, " version:%d.%02d.%02d\n", MAJOR_VERSION,  MINOR_VERSION, PATCH_LEVEL);
                                                                                             ^
exit status 1
invalid digit "8" in octal constant

And there I had to use 07 version

**Comment by pan-sattan** [comment]
[data.txt](https://github.com/zs6buj/FrSky-Passthru-To-WiFi-and-or-Bluetooth/files/7117190/data.txt)
here is log

**Comment by pan-sattan** [comment]
adn here is if I disable all debug, only #define Debug_FrSkyD_Flight_Mode will stay
[data.txt](https://github.com/zs6buj/FrSky-Passthru-To-WiFi-and-or-Bluetooth/files/7117211/data.txt)

**Comment by pan-sattan** [comment]
[data.txt](https://github.com/zs6buj/FrSky-Passthru-To-WiFi-and-or-Bluetooth/files/7117218/data.txt)
here is better text for reading.... 
I am using prearm switch, thats the reason of "2" flag, but at the end is "5" for arming and thats even in my radio if I check telemetry... so look like 5 flag is armed hint

**Comment by pan-sattan** [comment]
and thats strange, because in all documentations is that arm is on 4 flag
https://github.com/iNavFlight/inav/blob/master/docs/Telemetry.md
https://github.com/betaflight/betaflight/blob/master/docs/Telemetry.md

**Comment by zs6buj** [comment]
Thanks for feedback. I'm typing on my phone, so sorry for typos. 

I've extracted the arm_flag for debug, and also used pin 34 for homepin. This pin must go high (3.3v) for true.

Please try.

**Comment by pan-sattan** [comment]
ah, so its pul up method... now is it clear... means other buttons has the same config?
I will try... thank you

**Comment by pan-sattan** [comment]
yes, now I can see flag #5 after arming...

[data.txt](https://github.com/zs6buj/FrSky-Passthru-To-WiFi-and-or-Bluetooth/files/7123867/data.txt)

**Comment by zs6buj** [comment]
I've posted V2.18.09 for testing **Set_Home_On_Arm**. It will only work if you have a good GPS lock, obviously.

A lot of code changes were necessary to include the **Set_Home_On_Arm** in a tidy way, and I can't test here right now, so we might have to sort out a few bugs.  It should also work for Mavlink and other protocols. I can probably test Mavlink  and FrSky X-mode in the next day or two, commitments allowing.

**Comment by pan-sattan** [comment]
Ok I have room for testing tomorrow with gps_lock

**Comment by pan-sattan** [comment]
I went out, have locked gps, then armed quad... moving around, but tracker is still dont moving... dont have log... I thing somewhere at home have openlog, maybe I can connect it to esp32, but I am not sure about pinout...
![16311866271937280109758686341547](https://user-images.githubusercontent.com/59567959/132677297-c63b60fa-c1a0-48b3-b39c-d21cb10d95ac.jpg)

**Comment by pan-sattan** [comment]
here are two different flight logs:

[data.txt](https://github.com/zs6buj/FrSky-Passthru-To-WiFi-and-or-Bluetooth/files/7135953/data.txt)
[data2.txt](https://github.com/zs6buj/FrSky-Passthru-To-WiFi-and-or-Bluetooth/files/7135954/data2.txt)

**Comment by pan-sattan** [comment]
OK, maybe that one:
payload of FrSky message 0x400 is 30005 that menas arm_flag should be 5, but is 3
and thats reason why motArmed is still 0 I thing

gpsGood:1  gpsfixGood:1  lonGood:1  latGood:1  altGood:1  hdgGood:1  boxhdgGood:1 
gpsGood:1  gpsfixGood:1  lonGood:1  latGood:1  altGood:1  hdgGood:1  boxhdgGood:1 
gpsGood:1  gpsfixGood:1  lonGood:1  latGood:1  altGood:1  hdgGood:1  boxhdgGood:1 
FrSky 0x400 payload=30005 pt400_arm_flag=3  motArmed=0

**Comment by pan-sattan** [comment]
and somewhere I am using auto leveling mode, thats the reason of #1 here or #2 and others... depends on firmware 
payload=20015

**Comment by zs6buj** [comment]
Hi pan-sattan

I went to dig one of my tracker boxes out of a storage facility to test here. Now I'm using Mavlink from SITL on Ubuntu laptop, into Mav2PT, and then BT Mavlink out. This is just for testing Mavlink arming, but should also generally apply to FrSky D 0x400 arming if we get the arming flag correct.

![20210911_123041 (Phone)](https://user-images.githubusercontent.com/12892533/132946515-a8e3e7f2-8430-4794-a374-72357d6f3067.jpg)

So, I have posted V2.18.9 Debug again. Please could you flash and test like before.

**Comment by pan-sattan** [comment]
Hi,
here is new LOG
[arm.txt](https://github.com/zs6buj/FrSky-Passthru-To-WiFi-and-or-Bluetooth/files/7182845/arm.txt)

**Comment by zs6buj** [comment]
Hi pan-sattan,

Thanks for this. Did you ever arm the vehicle? The log shows some status changes in the 0x400 message type, but the least significant digit never changes to 3. In your previous log it did change to 3.

**Comment by pan-sattan** [comment]
the truth is, that I wait for gps log and then I armed my quad for some time, but didnt fly anywhere

**Comment by zs6buj** [comment]
It's strange that we get 0x400 message type payload changing like this:
10002
20002
30002
10002
Anyway, I also made a small change again in v2.18.09 (Debug folder).

When you get the time could you try again. Look at the log and see if 
the least significant digit ever goes to 3, like before.

Or identify the value when you arm.  
FrSky 0x400 payload=10002

**Comment by zs6buj** [comment]
I went back to data2.txt and we got this:

FrSky 0x400 payload=30005

**Comment by pan-sattan** [comment]
with this version finaly payload looks good, like in radio Tmp1 and firstime tracker was able to rotate with both servos... thank you... 
now I have to calibrate compass, etc...

here is the LOG
[tracker.txt](https://github.com/zs6buj/FrSky-Passthru-To-WiFi-and-or-Bluetooth/files/7189796/tracker.txt)

and I saw that in telemetry HUB is still 0 GPS sats...
https://user-images.githubusercontent.com/59567959/133887020-2a305be2-7ac7-435f-b9a8-27dea24a6248.mp4

**Comment by zs6buj** [comment]
Stale. Closed.
