### ISSUE TITLE
Compile issue

### ISSUE THREAD

**Issue by shro70** [zs6buj/FrSky-Passthru-To-WiFi-and-or-Bluetooth#2]
Hello .
I'm trying to compile for ESP8286 variant 3  ( Lolin D1 mini ) but I get a compile error if I select D1 mini or D1 mini clone  as board in Arduino ide .
![20220130_130426](https://user-images.githubusercontent.com/39678033/151698849-93aa2cb6-e0c7-481e-ab79-d2e1bd57dbad.jpg)

If I select generic esp8286 it show another error 
![20220130_130204](https://user-images.githubusercontent.com/39678033/151698861-56fa0217-ffca-4d23-a8cc-6fb8c7053b49.jpg)

Can you help me ?
The board I'm trying to use
https://a.aliexpress.com/_ujipK6

**Comment by zs6buj** [comment]
@shro70

Thanks for the feedback, and that looks like a nice board.  We are seeing some more esp8266 boards with usb support.

I cleaned up the esp8266 build, and excluded #define Support_SBUS_Out for now. If you need sbus support let me know, but then please propose a pin to use on your board.

**Comment by shro70** [comment]
I will give a try. I don't think I need sbus out. I want to send the sport and fport telemetry from my tX16s to your tracker and my Android phone.
Thanks for the quick answer again.

**Comment by shro70** [comment]
I  just noticed you updated MavlinkToPassthru instead of FrskyPassthruToWifi and Bluetooth

**Comment by zs6buj** [comment]
@shro70:

Oops! Ok, they are based on similar code. I'll do FrSky-Passthru-To-WiFi-and-or-BT as soon as I get a chance.

**Comment by zs6buj** [comment]
Fixed. V0.0.5. I also shortened the long-winded repo name to FrSkyToWiFiBT

**Comment by shro70** [comment]
if i select generic esp8266 as board :
![Capture](https://user-images.githubusercontent.com/39678033/152019501-136b132d-6fd6-4fbb-9e88-8bd9525e2b8d.JPG)

if i select lolin wemos D1 mini 
![Capture](https://user-images.githubusercontent.com/39678033/152019896-8112306a-4185-4b29-be93-eadf6e53298c.JPG)

**Comment by zs6buj** [comment]
It looks like you selected Autobaud. I'll look at that tomorrow.  You must select D1 mini.

**Comment by shro70** [comment]
No worries. I don't plan to fly my planes  before the end of winter .
I can't find any baud setting. If you mean protocol I selected smartport not autoprotocol

**Comment by zs6buj** [comment]
Could you post your config.h

**Comment by shro70** [comment]
changed the extension to txt. github won't let me upload a .h [config.txt](https://github.com/zs6buj/FrSkyToWiFiBT/files/7982176/config.txt)

**Comment by zs6buj** [comment]
It's compiling here with your config.h. Strange.


![image](https://user-images.githubusercontent.com/12892533/152111114-37b43a41-29cd-491e-8a09-f624321bc338.png)

**Comment by shro70** [comment]
Indeed. I will try to reinstall Arduino ide and all the libraries.
